# VPS代理管理系统告警规则

groups:
  # 系统级告警
  - name: system.rules
    rules:
      - alert: HighCpuUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "系统CPU使用率过高"
          description: "CPU使用率在 {{ $labels.instance }} 上超过80%超过5分钟"

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 20
        for: 3m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "系统内存使用率过高"
          description: "内存使用率在 {{ $labels.instance }} 上超过80%"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "磁盘空间不足"
          description: "磁盘空间在 {{ $labels.instance }} 上低于20%"

  # 应用级告警
  - name: application.rules
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "服务不可用"
          description: "{{ $labels.job }} 服务在 {{ $labels.instance }} 上不可用"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "高错误率检测"
          description: "{{ $labels.job }} 的错误率超过10%"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "高响应时间检测"
          description: "{{ $labels.job }} 的95%的请求超过1秒"

  # 数据库告警
  - name: database.rules
    rules:
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL数据库不可用"
          description: "PostgreSQL数据库未响应"

      - alert: PostgresqlTooManyConnections
        expr: sum by (instance) (pg_stat_activity_count) > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL连接数过多"
          description: "PostgreSQL有超过80个连接"

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis缓存不可用"
          description: "Redis缓存未响应"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis内存使用率过高"
          description: "Redis内存使用率超过90%"

  # 业务级告警
  - name: business.rules
    rules:
      - alert: ProxyInstanceDown
        expr: proxy_instance_up == 0
        for: 2m
        labels:
          severity: critical
          service: proxy
        annotations:
          summary: "代理实例不可用"
          description: "{{ $labels.protocol }} 代理实例 {{ $labels.instance }} 不可用"

      - alert: HighProxyLatency
        expr: avg by (instance, protocol) (proxy_response_time_seconds) > 2
        for: 5m
        labels:
          severity: warning
          service: proxy
        annotations:
          summary: "代理延迟过高"
          description: "{{ $labels.protocol }} 代理 {{ $labels.instance }} 延迟过高"

      - alert: ProxyConnectionFailure
        expr: rate(proxy_connection_errors_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: proxy
        annotations:
          summary: "代理连接失败率过高"
          description: "{{ $labels.protocol }} 代理连接失败率过高"

  # 安全告警
  - name: security.rules
    rules:
      - alert: TooManyLoginFailures
        expr: increase(auth_login_failures_total[5m]) > 10
        for: 0m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "登录失败次数过多"
          description: "来自 {{ $labels.source_ip }} 的5分钟内登录失败超过10次"

      - alert: SuspiciousActivity
        expr: rate(http_requests_total{status="403"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "检测到可疑活动"
          description: "403响应率过高，可能遭受攻击"

      - alert: SSLCertificateExpiry
        expr: (ssl_cert_not_after - time()) / 86400 < 30
        for: 0m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "SSL证书即将过期"
          description: "{{ $labels.instance }} 的SSL证书将在30天内过期"