# 代理管理系统告警规则

groups:
  # 系统级告警
  - name: system.rules
    rules:
      - alert: HighCpuUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 20
        for: 3m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Disk space is low"
          description: "Disk space is below 20% on {{ $labels.instance }}"

  # 应用级告警
  - name: application.rules
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is down on {{ $labels.instance }}"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for {{ $labels.job }}"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High response time detected"
          description: "95% of requests take more than 1 second for {{ $labels.job }}"

  # 数据库告警
  - name: database.rules
    rules:
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"

      - alert: PostgresqlTooManyConnections
        expr: sum by (instance) (pg_stat_activity_count) > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Too many connections to PostgreSQL"
          description: "PostgreSQL has more than 80 connections"

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache is not responding"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is above 90%"

  # 业务级告警
  - name: business.rules
    rules:
      - alert: ProxyInstanceDown
        expr: proxy_instance_up == 0
        for: 2m
        labels:
          severity: critical
          service: proxy
        annotations:
          summary: "Proxy instance is down"
          description: "{{ $labels.protocol }} proxy instance {{ $labels.instance }} is down"

      - alert: HighProxyLatency
        expr: avg by (instance, protocol) (proxy_response_time_seconds) > 2
        for: 5m
        labels:
          severity: warning
          service: proxy
        annotations:
          summary: "High proxy latency detected"
          description: "{{ $labels.protocol }} proxy {{ $labels.instance }} has high latency"

      - alert: ProxyConnectionFailure
        expr: rate(proxy_connection_errors_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: proxy
        annotations:
          summary: "High proxy connection failure rate"
          description: "{{ $labels.protocol }} proxy has high connection failure rate"

      - alert: UnusualTrafficPattern
        expr: rate(proxy_bytes_total[1h]) > 1.5 * rate(proxy_bytes_total[24h] offset 1h)
        for: 10m
        labels:
          severity: info
          service: traffic
        annotations:
          summary: "Unusual traffic pattern detected"
          description: "Traffic is 50% higher than usual on {{ $labels.instance }}"

  # 安全告警
  - name: security.rules
    rules:
      - alert: TooManyLoginFailures
        expr: increase(auth_login_failures_total[5m]) > 10
        for: 0m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Too many login failures"
          description: "More than 10 login failures in the last 5 minutes from {{ $labels.source_ip }}"

      - alert: SuspiciousActivity
        expr: rate(http_requests_total{status="403"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Suspicious activity detected"
          description: "High rate of 403 responses, possible attack attempt"

      - alert: SSLCertificateExpiry
        expr: (ssl_cert_not_after - time()) / 86400 < 30
        for: 0m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in less than 30 days"